### ISSUE TITLE
Erro no reduce que mescla os resultados da API do Meetup

### ISSUE THREAD

**Issue by fmoliveira** [comunidadescampinas/agenda-api#14]
Mensagem de erro:

```
{
"status": "error",
"message": "TypeError: Reduce of empty array with no initial value"
}
```

**Comment by fmoliveira** [comment]
O problema é aqui:

```js
res
        .filter(i => !!i)
        .reduce( (todos, atual) => ({
```

Após filtrar as responses diferentes de nula, o reduce recebeu um array vazio. (lib.js:50)

Todas as respostas estão nulas porque eu fiz vários deploys agora de pouco para testar o upgrade para o Node.js 8 no Heroku (para que funcionasse o promisify nativo), e com isto, gastei a cota de 200 requests por hora.

Precisamos checar se tem alguma response válida antes de fazer o reduce.

**Comment by victorperin** [comment]
Ok, vou dar uma olhada aqui

**Comment by victorperin** [comment]
Consegui reproduzir o erro removendo a key do meetup. Depois do deploy, só verifica se a key ainda está na heroku.

**Comment by fmoliveira** [comment]
Topp!! Já está funcionando!!

Valeu @victorperin ! 😉
